INSERT INTO tb_filme (titulo, genero, diretor, ano, estoque, lancamento) VALUES
('O Poderoso Chefão', 'Drama', 'Francis Ford Coppola', 1972, 12, false),
('Pulp Fiction', 'Crime', 'Quentin Tarantino', 1994, 8, false),
('Matrix', 'Sci-Fi', 'Lana Wachowski', 1999, 15, false),
('Forrest Gump', 'Drama', 'Robert Zemeckis', 1994, 10, false),
('Clube da Luta', 'Drama', 'David Fincher', 1999, 7, false),
('Interestelar', 'Sci-Fi', 'Christopher Nolan', 2014, 9, false),
('A Origem', 'Sci-Fi', 'Christopher Nolan', 2010, 13, false),
('O Senhor dos Anéis: A Sociedade do Anel', 'Fantasia', 'Peter Jackson', 2001, 11, false),
('O Senhor dos Anéis: O Retorno do Rei', 'Fantasia', 'Peter Jackson', 2003, 14, false),
('Star Wars: Episódio IV - Uma Nova Esperança', 'Sci-Fi', 'George Lucas', 1977, 20, false),
('Jurassic Park', 'Ação', 'Steven Spielberg', 1993, 17, false),
('Gladiador', 'Ação', 'Ridley Scott', 2000, 6, false),
('Titanic', 'Romance', 'James Cameron', 1997, 16, false),
('Avatar', 'Fantasia', 'James Cameron', 2009, 18, false),
('O Silêncio dos Inocentes', 'Suspense', 'Jonathan Demme', 1991, 5, false),
('Os Infiltrados', 'Crime', 'Martin Scorsese', 2006, 10, false),
('Mad Max: Estrada da Fúria', 'Ação', 'George Miller', 2015, 9, false),
('O Rei Leão', 'Animação', 'Roger Allers', 1994, 12, false),
('Toy Story', 'Animação', 'John Lasseter', 1995, 13, false),
('Homem-Aranha: No Aranhaverso', 'Animação', 'Bob Persichetti', 2018, 14, false),
('Deadpool', 'Ação', 'Tim Miller', 2016, 7, false),
('Os Vingadores', 'Ação', 'Joss Whedon', 2012, 19, false),
('Batman: O Cavaleiro das Trevas', 'Ação', 'Christopher Nolan', 2008, 15, false),
('Guardiões da Galáxia', 'Ação', 'James Gunn', 2014, 10, false),
('Dunkirk', 'Guerra', 'Christopher Nolan', 2017, 8, false),
('Coringa', 'Drama', 'Todd Phillips', 2019, 9, false),
('La La Land', 'Musical', 'Damien Chazelle', 2016, 11, false),
('A Bela e a Fera', 'Fantasia', 'Bill Condon', 2017, 12, false),
('Homem de Ferro', 'Ação', 'Jon Favreau', 2008, 16, false),
('Capitão América: O Soldado Invernal', 'Ação', 'Anthony Russo', 2014, 9, false),
('Thor: Ragnarok', 'Ação', 'Taika Waititi', 2017, 13, false),
('Pantera Negra', 'Ação', 'Ryan Coogler', 2018, 17, false),
('Star Wars: O Império Contra-Ataca', 'Sci-Fi', 'Irvin Kershner', 1980, 14, false),
('O Grande Lebowski', 'Comédia', 'Joel Coen', 1998, 6, false),
('Jurassic World', 'Ação', 'Colin Trevorrow', 2015, 10, false),
('Piratas do Caribe: A Maldição do Pérola Negra', 'Aventura', 'Gore Verbinski', 2003, 12, false),
('O Exorcista', 'Terror', 'William Friedkin', 1973, 7, false),
('O Sexto Sentido', 'Suspense', 'M. Night Shyamalan', 1999, 11, false),
('Toy Story 3', 'Animação', 'Lee Unkrich', 2010, 14, false),
('O Labirinto do Fauno', 'Fantasia', 'Guillermo del Toro', 2006, 10, false),
('A Rede Social', 'Drama', 'David Fincher', 2010, 9, false),
('007 - Cassino Royale', 'Ação', 'Martin Campbell', 2006, 12, false),
('O Jogo da Imitação', 'Drama', 'Morten Tyldum', 2014, 10, false),
('Whiplash', 'Drama', 'Damien Chazelle', 2014, 11, false),
('A Viagem de Chihiro', 'Animação', 'Hayao Miyazaki', 2001, 14, false);

INSERT INTO tb_filme (titulo, genero, diretor, ano, estoque, lancamento) VALUES
('Os Oito Odiados', 'Faroeste', 'Quentin Tarantino', 2015, 3, false),
('O Irlandês', 'Drama', 'Martin Scorsese', 2019, 2, false),
('O Regresso', 'Aventura', 'Alejandro G. Iñárritu', 2015, 1, false),
('A Chegada', 'Sci-Fi', 'Denis Villeneuve', 2016, 4, false),
('Blade Runner 2049', 'Sci-Fi', 'Denis Villeneuve', 2017, 3, false),
('Moonlight', 'Drama', 'Barry Jenkins', 2016, 2, false),
('O Lobo de Wall Street', 'Comédia', 'Martin Scorsese', 2013, 1, false),
('Parasita', 'Drama', 'Bong Joon Ho', 2019, 2, false),
('O Discurso do Rei', 'Drama', 'Tom Hooper', 2010, 4, false),
('Gravidade', 'Sci-Fi', 'Alfonso Cuarón', 2013, 3, false),
('Birdman', 'Comédia', 'Alejandro G. Iñárritu', 2014, 2, false),
('Spotlight', 'Drama', 'Tom McCarthy', 2015, 1, false),
('A Forma da Água', 'Fantasia', 'Guillermo del Toro', 2017, 3, false),
('Os Miseráveis', 'Musical', 'Tom Hooper', 2012, 4, false),
('Bohemian Rhapsody', 'Musical', 'Bryan Singer', 2018, 2, false),
('Rocketman', 'Musical', 'Dexter Fletcher', 2019, 2, false),
('O Rei do Show', 'Musical', 'Michael Gracey', 2017, 4, false),
('Frozen', 'Animação', 'Chris Buck', 2013, 3, false),
('Divertida Mente', 'Animação', 'Pete Docter', 2015, 4, false),
('Moana', 'Animação', 'Ron Clements', 2016, 3, false),
('Soul', 'Animação', 'Pete Docter', 2020, 2, false),
('Elementos', 'Animação', 'Peter Sohn', 2023, 4, true),
('Encanto', 'Animação', 'Jared Bush', 2021, 2, false),
('Raya e o Último Dragão', 'Animação', 'Don Hall', 2021, 3, false),
('Luca', 'Animação', 'Enrico Casarosa', 2021, 2, false),
('Lightyear', 'Animação', 'Angus MacLane', 2022, 1, true),
('Viva: A Vida é uma Festa', 'Animação', 'Lee Unkrich', 2017, 2, false),
('O Bom Dinossauro', 'Animação', 'Peter Sohn', 2015, 3, false),
('Zootopia', 'Animação', 'Byron Howard', 2016, 4, false),
('Sing', 'Animação', 'Garth Jennings', 2016, 3, false),
('Minions', 'Animação', 'Pierre Coffin', 2015, 2, false),
('Meu Malvado Favorito', 'Animação', 'Pierre Coffin', 2010, 4, false),
('Os Croods', 'Animação', 'Kirk DeMicco', 2013, 3, false),
('Tá Dando Onda', 'Animação', 'Ash Brannon', 2007, 1, false),
('Kung Fu Panda', 'Animação', 'Mark Osborne', 2008, 4, false),
('Shrek', 'Animação', 'Andrew Adamson', 2001, 2, false),
('Madagascar', 'Animação', 'Eric Darnell', 2005, 3, false),
('A Era do Gelo', 'Animação', 'Chris Wedge', 2002, 4, false),
('Procurando Nemo', 'Animação', 'Andrew Stanton', 2003, 2, false),
('Up: Altas Aventuras', 'Animação', 'Pete Docter', 2009, 3, false),
('Wall-E', 'Animação', 'Andrew Stanton', 2008, 4, false),
('Os Incríveis', 'Animação', 'Brad Bird', 2004, 2, false),
('Carros', 'Animação', 'John Lasseter', 2006, 4, false),
('Ratatouille', 'Animação', 'Brad Bird', 2007, 3, false),
('Valente', 'Animação', 'Brenda Chapman', 2012, 2, false),
('Enrolados', 'Animação', 'Nathan Greno', 2010, 4, false),
('Detona Ralph', 'Animação', 'Rich Moore', 2012, 3, false);
